name = "independenceee/cip68generator"
version = "0.0.0"
compiler = "v1.1.0"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'independenceee/cip68generator'"

[repository]
user = "independenceee"
project = "cip68generator"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[[dependencies]]
name = "logical-mechanism/assist"
version = "v0.5.0"
source = "github"

[config]
