test test_deposit_success() {
  True
}

test test_deposit_fail_reduce_lovelace() {
  True
}

test test_deposit_fail_changed_receiver() {
  True
}

test test_signature_one_owner() {
    True
}

test test_signature_multi_owners() {
    True
}

test test_signature_fail_not_owner() {
    True
}

test test_signature_fail_duplicate_signer() {
    True
}

test test_signature_fail_modified_datum() {
    True
}

test test_signature_fail_missing_previous_signers () {
    True
}

test test_execute_success_partial_spend() {
    True
}

test test_execute_success_full_spend() {
    True
}

test test_execute_fail_insufficient_threshold() {
    True
}

test test_execute_fail_wrong_receiver() {
    True
}

test test_execute_fail_exceed_allowance() {
    True
}

test test_execute_fail_not_resetting_signers() {
    True
}
